const main = () => {
	console.log("hello world!");
};

try {
	main();
} catch (e) {
	console.error(e);
}
